In [1]:
import numpy as np

In [28]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print(a_ndarray)
print(b_ndarray)

[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


# [Problem 1] Matrix product is calculated manually

In [29]:
## matrix product is done by following order a[0][0]*b[0][0] + a[0][1] * b[1][0] + a[0][2]*b[2][0] and then goes on
## for example, given matrix products's [0][0] element will be -1*0+2*0+3*2=6, i name product as new_matrix 
## new_matrix[0][0]=(-1*0) + 2*0 + 3*2 = 0 + 2 + 6 = 6
## new_matrix[0][1]=(-1*2) + 2*2 + 3*9 = (-2) + 4 + 27 = 29
## new_matrix[0][2]=(-1*1) + (2*-8) + (3*-1) = (-1) - 16 - 3 = -20
## new_matrix[1][0]=4*0 + (-5*0) + 6*2 = 0 - 0 + 12 = 12
## new_matrix[1][1]=4*2 + (-5*2) + 6*9 = 8 - 10 + 54 = 52
## new_matrix[1][2]=4*1 + (-5*-8) + (6*-1) = 4 + 40 - 6 = 38
## new_matrix[2][0]=7*0 + 8*0 + (-9*2) = 0 + 0 - 18 = -18
## new_matrix[2][1]=-7*2 + 8*2 + (-9*9) = 14 + 16 - 81 = -51
## new_matrix[2][2]=-7*1 + (8*-8) + (-9*-1) = 7 - 64 + 9 = -48
## so product will be [[  6  29 -20], [ 12  52  38], [-18 -51 -48]]

In [7]:
## result will be [[  6,  29, -20], [ 12,  52,  38], [-18, -51, -48]]

# [Problem 2] Calculation by NumPy function

In [8]:
result = np.dot(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [9]:
result = np.matmul(a_ndarray, b_ndarray)
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


In [10]:
result = a_ndarray@b_ndarray
print(result)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# [Problem 3] Implementation of calculation of a certain element

In [11]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [16]:
result = [[0,0,0], [0,0,0], [0,0,0]]
for i in range(len(a_ndarray)):
    for j in range(len(b_ndarray[0])):
        for k in range(len(b_ndarray)):
            result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
print(result)

[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[0, 0, 0], [0, 0, 0], [0, 0, 0]]
[[6, 0, 0], [0, 0, 0], [0, 0, 0]]
[[6, -2, 0], [0, 0, 0], [0, 0, 0]]
[[6, 2, 0], [0, 0, 0], [0, 0, 0]]
[[6, 29, 0], [0, 0, 0], [0, 0, 0]]
[[6, 29, -1], [0, 0, 0], [0, 0, 0]]
[[6, 29, -17], [0, 0, 0], [0, 0, 0]]
[[6, 29, -20], [0, 0, 0], [0, 0, 0]]
[[6, 29, -20], [0, 0, 0], [0, 0, 0]]
[[6, 29, -20], [0, 0, 0], [0, 0, 0]]
[[6, 29, -20], [12, 0, 0], [0, 0, 0]]
[[6, 29, -20], [12, 8, 0], [0, 0, 0]]
[[6, 29, -20], [12, -2, 0], [0, 0, 0]]
[[6, 29, -20], [12, 52, 0], [0, 0, 0]]
[[6, 29, -20], [12, 52, 4], [0, 0, 0]]
[[6, 29, -20], [12, 52, 44], [0, 0, 0]]
[[6, 29, -20], [12, 52, 38], [0, 0, 0]]
[[6, 29, -20], [12, 52, 38], [0, 0, 0]]
[[6, 29, -20], [12, 52, 38], [0, 0, 0]]
[[6, 29, -20], [12, 52, 38], [-18, 0, 0]]
[[6, 29, -20], [12, 52, 38], [-18, 14, 0]]
[[6, 29, -20], [12, 52, 38], [-18, 30, 0]]
[[6, 29, -20], [12, 52, 38], [-18, -51, 0]]
[[6, 29, -20], [12, 52, 38], [-18, -51, 7]]
[[6, 29, -20], [12, 52, 38], [-18, -51, -

# [Problem 4] Creating a function that performs matrix multiplication

In [17]:
def calculate_product(a, b):
    """
    A function that calculates product of matrixes

    Parameters
    ----------
    a: matrix
        a matrix
    b: matrix
        b matrix

    Returns
    -------
    result: matrix
        product of given matrixes
    """
    
    result = [[0,0,0], [0,0,0], [0,0,0]]
    for i in range(len(a_ndarray)):
        for j in range(len(b_ndarray[0])):
            for k in range(len(b_ndarray)):
                result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
    return result

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
res = calculate_product(a_ndarray, b_ndarray)
print(res)

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]


# [Problem 5] Judge the input whose calculation is not defined

In [18]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [19]:
res = np.dot(d_ndarray, e_ndarray)
print(res)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [21]:
def calculate_product(a, b):
    """
    A function that calculates product of matrixes

    Parameters
    ----------
    a: matrix
        a matrix
    b: matrix
        b matrix

    Returns
    -------
    result: matrix
        product of given matrixes
    """
    if len(a) != len(b[0]):
        print("matrix shapes are not correct")
    else:
        result = [[0,0,0], [0,0,0], [0,0,0]]
        for i in range(len(a_ndarray)):
            for j in range(len(b_ndarray[0])):
                for k in range(len(b_ndarray)):
                    result[i][j] += a_ndarray[i][k] * b_ndarray[k][j]
        return result

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
res = calculate_product(d_ndarray, e_ndarray)
print(res)

matrix shapes are not correct
None


# [Problem 6] Transposition

In [22]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

In [24]:
print(e_ndarray.T)

[[-9  6]
 [ 8 -5]
 [ 7  4]]


In [25]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
res = calculate_product(d_ndarray, e_ndarray.T)
print(res)

[[6, 29, -20], [12, 52, 38], [-18, -51, -48]]
